# -*- coding: utf-8 -*-
"""Min Tic Sem 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJ7sRavlqFKulmuQFnxRbTeiejOEK7Zw

Librerias
"""

import numpy as np

a = np.array(list(range(1, 5)))
print(a)

print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

a[0] = -10
print(a[0], a[1], a[2])

b = np.array([[1, 200000, 3, 5, 6],[4, 5, 6, 7, 8]])

print(b.shape)
print(b)
b [0,0] = 1500
print(b)

print(b[0,0], b[0,1], b[1][1])

a = np.zeros((2,3,4))

print(a.shape)

print(a)

b = np.ones((2,3))
print(b.shape)
print(b)

# Arreglos
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape)
print(a)

b = a[:2, 1:3]
print(b)
print("-------------------")

b[0,0] = -9999
print(b)
print(a)

x = np.array([5,-4])
print(x.dtype)

x = np.array([1.0, 5.0])
print(x.dtype)

x = np.array([5, -4], dtype = np.int16)
print(x.dtype)

import numpy as np
x = np.array([[1,2,5],[3,4,6]], dtype = np.float128)
y = np.array([[5,6,-1],[7,8,-6]], dtype = np.float128)

print("suma")
print(x+y)

print(x**2)

print("raiz cuadrada")
print(np.sqrt(x))