# -*- coding: utf-8 -*-
"""MINTIC Reto_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ne3Gh3d88h3V_t9Z8ldvJqiF9BHNzfSe
"""

primeros = str(input())
nuevos = str(input())
jugadores_g = str(input())

contador_p = 0
contador_n = 0

for letra in jugadores_g:

  contador_p += primeros.count(letra)
  contador_n += nuevos.count(letra)

  if contador_n > contador_p:
    print("N", end = "")
  elif contador_p > contador_n:
    print("P", end = "")
  else:
    print("E", end = "")