# -*- coding: utf-8 -*-
"""MINTIC sem 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDfrxbXWHNf9fjWtmMfsHCQ17bv4ppJP

DICCIONARIOS
"""

# UNIR DICCIONARIOS (UPDATE)

dict_ports1 = {22:"SSH", 80:"Http"}
dict_ports2 = {53:"DNS", 443:"https"}
print(dict_ports1)

dict_ports1.update(dict_ports2)
print(dict_ports1)

# COMPARAR DICCIONARIOS se utilizan operadores logicos

a = {123:"Rojas", 87:"Rosas"} == {87:"Rosas", 123:"Rojas"}
print(a)

print({"Rosas":123} != {"rosas":123})

b = {123:"Rosas", 87:"rojas"} == {"Rosas":123, 87:"rojas"}
print(b)

# ACCERDER A DICCIONARIOS

puertos = {22:"SSH", 23:"Telnet", 80:"HTTP", 3306:"MySQL"}
protocolo = puertos[22]
print(protocolo)

# o

print(puertos[22])

# AGREGAR O MODIFICAR DICCIONARIOS

puertos = {80:"HTTP", 23:"SMTP", 443:"HTTPS"}
print(puertos)

puertos[23] = "Telnet"
print(puertos)

puertos[110] = "POP"
print(puertos)

# ELIMINAR ELEMENTOS DE UN DICCIONARIO

puertos = {22:"SSH", 23:"Telnet", 80:"HTTP", 3306:"MySQL"}
print(puertos)

del puertos[23]
print(puertos)

# CONSULTANDO UN DICCIONARIO

puertos = {80:"HTTP", 23:"SMTP", 443:"HTTPS"}
if 80 in puertos:
  print("yes")

if 110 not in puertos:
  print("no")
else:
  print("yes")

# ITERANDO EN UN DICCIONARIO

dict_ports = {22:"SSH", 23:"telnet", 80:"Http"}

for key in dict_ports:
  print(key) #imprime solo la llave
  print(key, dict_ports[key]) #imprime llave y valor

dict_ports = {22:"SSH", 23:"telnet", 80:"Http"}

for k,v in dict_ports.items(): # .items trae llave y valor
  print(k, "->", v)

# LONGITUD (len) EN DICCIONARIOS

puertos = {80:"HTTP", 23:"SMTP", 443:"HTTPS"}
print(len(puertos))

# OBTENER VALORES (get)

dict1 = {"a":1, "b":2, "c":3}

print(dict1.get("a"))

print(dict1.get("d", "clave no encontrada."))

# max, min

puertos = {80:"HTTP", 23:"SMTP", 443:"HTTPS"}

print(max(puertos))

print(min(puertos))

# LISTAS DE CLAVES Y VALORES (keys, values)

dict1 = {"a":1, "b":2, "c":3}

print(list(dict1.keys()))

print(list(dict1.values()))

# CONVERTIR A DICCIONARIOS (dict)

puertos = [[80, "http"], [20, "ftp"], [23, "telnet"]] #lista de listas
d_port = dict(puertos)
print(d_port)

puertos = [(20, "ftp"), (80, "http"), (23, "telnet")] # lista de tuplas
d_port = dict(puertos)
print(d_port)

# ELIMINAR ENTRADAS (clear) Eliminar diccionarios

dict_ports = {22:"SSH", 23:"telnet", 80:"Http"}
print(dict_ports)

dict_ports.clear()
print(dict_ports)

# COPIAR DICCIONARIOS (copy)

port = {80:"HTTP", 23:"SMTP", 443:"HTTPS"}
copy_port = port.copy()
false_copy = port
print(port)

print(copy_port)

print(false_copy)

# EJERCICIOS

midicc = {"a":3, "b":6, "c":1, "d":5}

print(sorted(list(midicc.values()))) #sorted para ordenarlos ascendente

# EJERCCIOS
dicc_a = {1:"a", 2:"b"}
dicc_b = {1:"e", 2:"b"}

if dicc_a == dicc_b:
  print("Si se encuentran")
else:
  print("No se encuentran")