# -*- coding: utf-8 -*-
"""MINTIC Reto 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E00qUBD4zcSdiQ7Ao5hVBQMdxFto8DwJ
"""

# secuencia de prueba:
#T,T,T,a,A,A,C,C,C,C,H,Z,Z,Z,O,O,O,H,M,F,F,F,F,F

lista1 = (input().upper()).split(",")

lista_jugadores = []
lista_victorias = []
let = lista1[0]
vic = 0
long = 0

for letra in lista1:
  long += 1
  if letra == let:
    let = letra
    vic += 1
    if len(lista1) == long:
      lista_jugadores.append(let)
      lista_victorias.append(vic)
  else:
    lista_jugadores.append(let)
    let = letra
    lista_victorias.append(vic)
    vic = 1
    if len(lista1) == long:
      lista_jugadores.append(let)
      lista_victorias.append(vic)

print(*lista_jugadores)
print(*lista_victorias)