# -*- coding: utf-8 -*-
"""MINTIC Reto_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KEUYC-OcmTlZLiTbb-_VBU0ptqbbdEm
"""

cl = int(input())
cc = int(cl * 2 + 4)
cb = int((cl + cc) / 5)

print(cl, cc, cb)

if cb <=20:
  print("uno")
elif (cb > 20) and (cb <= 30):
  print("dos")
elif (cb > 30) and (cb <= 50):
  print("tres")
else:
  print("cuatro")