# -*- coding: utf-8 -*-
"""Reto 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cFTFK9mWhXVqhL6-SzVGA56PgQC9xJtj
"""

import json

# {"carretilla": 37367, "huevo_y_cuchara": 41400, "comer": 57591, "tiro_blanco": 58511, "bombas_agua": 94431}
# carretilla futbol piscina tibetano encostalados comer

medallas = input()
medallas1 = json.loads(medallas)
lista_medallas = medallas1.items()
#print(lista_medallas, type(lista_medallas))

premios = input()
lista_premios = premios.split()
#print(lista_premios, type(lista_premios))

total_ganado = 0
juegos_ganados = []

for premio in lista_premios:
  for medalla in lista_medallas:
    ganado = medalla[1]
    medalla = medalla[0]
    if premio == medalla:
      total_ganado += ganado
      juegos_ganados.append(str(medalla))

print(str(total_ganado))
print(*juegos_ganados)